Julia Version 1.6.0-DEV.1175
Commit 7f7ab69fd3 (2020-10-09 21:29 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD EPYC 7502 32-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-10.0.1 (ORCJIT, znver2)
Environment:
  JULIA_DEPOT_PATH = ::/usr/local/share/julia
  JULIA_NUM_THREADS = 2

  Resolving package versions...
  Installed Scratch ─ v1.0.3
  Installed PyVenvs ─ v0.1.0
Updating `~/.julia/environments/v1.6/Project.toml`
  [900dd30e] + PyVenvs v0.1.0
Updating `~/.julia/environments/v1.6/Manifest.toml`
  [900dd30e] + PyVenvs v0.1.0
  [6c6a2e73] + Scratch v1.0.3
  [56f22d72] + Artifacts
  [2a0f44e3] + Base64
  [ade2ca70] + Dates
  [b77e0a4c] + InteractiveUtils
  [76f85450] + LibGit2
  [8f399da3] + Libdl
  [d6f4376e] + Markdown
  [44cfe95a] + Pkg
  [de0858da] + Printf
  [3fa0cd96] + REPL
  [9a3f8284] + Random
  [ea8e919c] + SHA
  [9e88b42a] + Serialization
  [6462fe0b] + Sockets
  [fa267f1f] + TOML
  [cf7118a7] + UUIDs
  [4ec0a83e] + Unicode
    Testing PyVenvs
┌ Error: Pkg.Types.PkgError("Error building `PyCall`: \nPREFIX=/home/pkgeval/.julia/conda/3\nWARNING: md5sum mismatch of tar archive\nexpected: 728a5c953844917b24246080968d03b8\n     got: 1fe697aace1c17362f30a23f17eaf1ef  -\nUnpacking payload ...\nTraceback (most recent call last):\n  File \"entry_point.py\", line 76, in <module>\n  File \"tarfile.py\", line 2024, in extractall\n  File \"tarfile.py\", line 2065, in extract\n  File \"tarfile.py\", line 2137, in _extract_member\n  File \"tarfile.py\", line 2186, in makefile\n  File \"tarfile.py\", line 249, in copyfileobj\ntarfile.ReadError: unexpected end of data\n[196] Failed to execute script entry_point\n\r  0%|          | 0/1 [00:00<?, ?it/s]\r                                     \rconcurrent.futures.process._RemoteTraceback: \n'''\nTraceback (most recent call last):\n  File \"concurrent/futures/process.py\", line 368, in _queue_management_worker\n  File \"multiprocessing/connection.py\", line 251, in recv\nTypeError: __init__() missing 1 required positional argument: 'msg'\n'''\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"entry_point.py\", line 69, in <module>\n  File \"concurrent/futures/process.py\", line 484, in _chain_from_iterable_of_lists\n  File \"concurrent/futures/_base.py\", line 611, in result_iterator\n  File \"concurrent/futures/_base.py\", line 439, in result\n  File \"concurrent/futures/_base.py\", line 388, in __get_result\nconcurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.\n[199] Failed to execute script entry_point\n┌ Info: Using the Python distribution in the Conda package by default.\n└ To use a different Python version, set ENV[\"PYTHON\"]=\"pythoncommand\" and re-run Pkg.build(\"PyCall\").\n[ Info: Downloading miniconda installer ...\n[ Info: Installing miniconda ...\nERROR: LoadError: failed process: Process(`/home/pkgeval/.julia/conda/3/installer.sh -b -f -p /home/pkgeval/.julia/conda/3`, ProcessExited(1)) [1]\n\nStacktrace:\n  [1] pipeline_error\n    @ ./process.jl:525 [inlined]\n  [2] run(::Cmd; wait::Bool)\n    @ Base ./process.jl:440\n  [3] run\n    @ ./process.jl:438 [inlined]\n  [4] _install_conda(env::String, force::Bool)\n    @ Conda ~/.julia/packages/Conda/3rPhK/src/Conda.jl:169\n  [5] _install_conda(env::String)\n    @ Conda ~/.julia/packages/Conda/3rPhK/src/Conda.jl:155\n  [6] runconda(args::Cmd, env::String)\n    @ Conda ~/.julia/packages/Conda/3rPhK/src/Conda.jl:112\n  [7] add(pkg::String, env::String; channel::String)\n    @ Conda ~/.julia/packages/Conda/3rPhK/src/Conda.jl:188\n  [8] add\n    @ ~/.julia/packages/Conda/3rPhK/src/Conda.jl:187 [inlined]\n  [9] top-level scope\n    @ ~/.julia/packages/PyCall/BcTLp/deps/build.jl:84\n [10] include(fname::String)\n    @ Base.MainInclude ./client.jl:444\n [11] top-level scope\n    @ none:5\nin expression starting at /home/pkgeval/.julia/packages/PyCall/BcTLp/deps/build.jl:43")
└ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Operations.jl:1457
Status `/tmp/jl_ciMZb1/Project.toml`
  [4c88cf16] Aqua v0.4.11
  [438e738f] PyCall v1.92.1
  [900dd30e] PyVenvs v0.1.0
  [44cfe95a] Pkg
  [8dfed614] Test
Status `/tmp/jl_ciMZb1/Manifest.toml`
  [4c88cf16] Aqua v0.4.11
  [8f4d0f93] Conda v1.4.1
  [682c06a0] JSON v0.21.1
  [1914dd2f] MacroTools v0.5.5
  [69de0a69] Parsers v1.0.11
  [438e738f] PyCall v1.92.1
  [900dd30e] PyVenvs v0.1.0
  [6c6a2e73] Scratch v1.0.3
  [81def892] VersionParsing v1.2.0
  [56f22d72] Artifacts
  [2a0f44e3] Base64
  [ade2ca70] Dates
  [b77e0a4c] InteractiveUtils
  [76f85450] LibGit2
  [8f399da3] Libdl
  [37e2e46d] LinearAlgebra
  [56ddb016] Logging
  [d6f4376e] Markdown
  [a63ad114] Mmap
  [44cfe95a] Pkg
  [de0858da] Printf
  [3fa0cd96] REPL
  [9a3f8284] Random
  [ea8e919c] SHA
  [9e88b42a] Serialization
  [6462fe0b] Sockets
  [fa267f1f] TOML
  [8dfed614] Test
  [cf7118a7] UUIDs
  [4ec0a83e] Unicode
    Testing Running tests...
Skipping Base.active_repl
Skipping Base.active_repl_backend
Skipping Base.Filesystem.JL_O_RANDOM
Skipping Base.Filesystem.JL_O_SEQUENTIAL
Skipping Base.Filesystem.JL_O_SHORT_LIVED
Skipping Base.Filesystem.JL_O_TEMPORARY
Skipping Base.BinaryPlatforms.compiler_abi
Skipping Base.active_repl
Skipping Base.active_repl_backend
Skipping Base.Filesystem.JL_O_RANDOM
Skipping Base.Filesystem.JL_O_SEQUENTIAL
Skipping Base.Filesystem.JL_O_SHORT_LIVED
Skipping Base.Filesystem.JL_O_TEMPORARY
Skipping Base.BinaryPlatforms.compiler_abi
Test Summary: | Pass  Total
test_aqua.jl  |    7      7
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt-get install python3-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/home/pkgeval/.julia/scratchspaces/900dd30e-34bf-4e23-831d-6809554238a5/pyvenv-CLI-VENV-0.1.0-49e2bf059941c4c5516639184921e340bb05a057/venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']

test_core.jl: Error During Test at /home/pkgeval/.julia/packages/PyVenvs/YgBvj/test/runtests.jl:4
  Got exception outside of a @test
  LoadError: InitError: failed process: Process(`python3 -m venv /home/pkgeval/.julia/scratchspaces/900dd30e-34bf-4e23-831d-6809554238a5/pyvenv-CLI-VENV-0.1.0-49e2bf059941c4c5516639184921e340bb05a057/venv`, ProcessExited(1)) [1]
  
  Stacktrace:
    [1] pipeline_error
      @ ./process.jl:525 [inlined]
    [2] run(::Cmd; wait::Bool)
      @ Base ./process.jl:440
    [3] run
      @ ./process.jl:438 [inlined]
    [4] mkvenv(path::String)
      @ PyVenvs.Implementations ~/.julia/packages/PyVenvs/YgBvj/src/core.jl:61
    [5] mkvenv(venv::PyVenvs.Implementations.PyVenv)
      @ PyVenvs.Implementations ~/.julia/packages/PyVenvs/YgBvj/src/core.jl:60
    [6] install(venv::PyVenvs.Implementations.PyVenv; upgrade::Bool)
      @ PyVenvs.Implementations ~/.julia/packages/PyVenvs/YgBvj/src/core.jl:130
    [7] install
      @ ~/.julia/packages/PyVenvs/YgBvj/src/core.jl:130 [inlined]
    [8] #5
      @ ~/.julia/packages/PyVenvs/YgBvj/src/core.jl:119 [inlined]
    [9] _with_python
      @ ~/.julia/packages/PyVenvs/YgBvj/src/core.jl:108 [inlined]
   [10] #init#4
      @ ~/.julia/packages/PyVenvs/YgBvj/src/core.jl:117 [inlined]
   [11] init
      @ ~/.julia/packages/PyVenvs/YgBvj/src/core.jl:117 [inlined]
   [12] __init__()
      @ CLIVenvExample ~/.julia/packages/PyVenvs/YgBvj/examples/CLIVenvExample/src/CLIVenvExample.jl:11
   [13] _include_from_serialized(path::String, depmods::Vector{Any})
      @ Base ./loading.jl:630
   [14] _require_from_serialized(path::String, cache::Base.TOMLCache)
      @ Base ./loading.jl:683
   [15] _require(pkg::Base.PkgId, cache::Base.TOMLCache)
      @ Base ./loading.jl:988
   [16] require(uuidkey::Base.PkgId, cache::Base.TOMLCache)
      @ Base ./loading.jl:871
   [17] require(into::Module, mod::Symbol)
      @ Base ./loading.jl:858
   [18] include(mod::Module, _path::String)
      @ Base ./Base.jl:389
   [19] include(x::String)
      @ Main.TestPyVenvs ~/.julia/packages/PyVenvs/YgBvj/test/runtests.jl:1
   [20] top-level scope
      @ ~/.julia/packages/PyVenvs/YgBvj/test/runtests.jl:13
   [21] top-level scope
      @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1219
   [22] include(fname::String)
      @ Base.MainInclude ./client.jl:444
   [23] top-level scope
      @ none:6
   [24] eval(m::Module, e::Any)
      @ Core ./boot.jl:360
   [25] exec_options(opts::Base.JLOptions)
      @ Base ./client.jl:261
   [26] _start()
      @ Base ./client.jl:485
  during initialization of module CLIVenvExample
  in expression starting at /home/pkgeval/.julia/packages/PyVenvs/YgBvj/test/test_core.jl:1
Test Summary: | Error  Total
test_core.jl  |     1      1
Test Summary: | Error  Total
test_core.jl  |     1      1
ERROR: LoadError: Some tests did not pass: 0 passed, 0 failed, 1 errored, 0 broken.
in expression starting at /home/pkgeval/.julia/packages/PyVenvs/YgBvj/test/runtests.jl:1

caused by: Some tests did not pass: 0 passed, 0 failed, 1 errored, 0 broken.
ERROR: Package PyVenvs errored during testing
Stacktrace:
  [1] pkgerror(msg::String)
    @ Pkg.Types /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Types.jl:52
  [2] test(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}; coverage::Bool, julia_args::Cmd, test_args::Cmd, test_fn::Nothing)
    @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Operations.jl:1609
  [3] test(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}; coverage::Bool, test_fn::Nothing, julia_args::Cmd, test_args::Cmd, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Pkg.API /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:331
  [4] test(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec})
    @ Pkg.API /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:318
  [5] #test#62
    @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:68 [inlined]
  [6] test
    @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:68 [inlined]
  [7] #test#61
    @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:66 [inlined]
  [8] test
    @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:66 [inlined]
  [9] test(pkg::String; kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Pkg.API /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:65
 [10] test(pkg::String)
    @ Pkg.API /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:65
 [11] top-level scope
    @ none:19
